import turtle
turtle.turtles()
turtle.bgcolor("black")
turtle.color("green")
turtle.circle(100)
turtle.right(15)
turtle.left(15)
turtle.circle(90)
turtle.right(12)
turtle.left(12)
turtle.circle(80)
turtle.right(11)
turtle.left(11)
turtle.circle(70)
turtle.right(10)
turtle.left(10)
turtle.circle(60)
turtle.right(9)
turtle.left(9)
turtle.circle(50)
turtle.right(8)
turtle.left(8)
turtle.circle(40)
turtle.right(7)
turtle.left(7)

